// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArV7seapHIs6bOjWdyxg-C61NaAkNNXjM',
    appId: '1:745425719035:web:93ed4619e14caed3e9ea5e',
    messagingSenderId: '745425719035',
    projectId: 'dawafind',
    authDomain: 'dawafind.firebaseapp.com',
    storageBucket: 'dawafind.firebasestorage.app',
    measurementId: 'G-8MWBND4VKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABfFH1kRTNYEukXNvu6pWt2hYYVwXVPzw',
    appId: '1:745425719035:android:25fc054f048be630e9ea5e',
    messagingSenderId: '745425719035',
    projectId: 'dawafind',
    storageBucket: 'dawafind.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCM3ksDARQ2q6CAq6qTVL26nntRo7MgCk',
    appId: '1:745425719035:ios:92dad994950bcfc3e9ea5e',
    messagingSenderId: '745425719035',
    projectId: 'dawafind',
    storageBucket: 'dawafind.firebasestorage.app',
    iosClientId: '745425719035-abv4tpt96pfreg54u6qjrn0t3ptqm9r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dawafind',
  );
}
